[font]
# The normal (roman) font family and style
normal.family = "MesloLGS NF"
normal.style  = "Regular"

# Optional: bold and italic faces
bold.family   = "MesloLGS NF"
bold.style    = "Bold"

italic.family = "MesloLGS NF"
italic.style  = "Oblique"

# Point size (floating-point OK)
size = 12.0

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
